name: Publishes package to registries and deploys the demo

permissions: 
  contents: write

on:
  push:
    tags:
    - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 18.12
        registry-url: https://registry.npmjs.org
    - name: Install dependencies
      run: yarn
    - name: Build lib
      working-directory: lib
      run: yarn build
    - name: Copy readme to lib folder
      run: cp README.md LICENSE lib/
    - name: Publish lib
      working-directory: lib
      run: yarn publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Build demo
      working-directory: demo
      run: yarn build
      env:
        PUBLIC_URL: /react-pin-field
    - name: Deploy demo
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: gh-pages
        folder: demo/build
